### PR TITLE
Refactor parse list param

### PR DESCRIPTION
**Pull request by sapk**
Refactor common code from LIST and NLST.
The goal is to fix a bug when receiving path with space in it. 
Only the path part after the last space and not the whole path was looked.

To do that, I search for the last -args and consider the rest as the path.

I added tests to confirm.

Extra: I did the same change as #38 for NLST and only open data after error checks

### CODE REVIEW

**Comment by lunny** [comment]
but why the CI is not triggered. It's strange.

**Comment by sapk** [comment]
None of commits PR seems to trigger CI maybe you need to activate some options on Circle CI: https://circleci.com/docs/1.0/fork-pr-builds/

**Comment by lunny** [comment]
@sapk done. Could you send a push to enforce the CI?

**Comment by sapk** [comment]
Done and tests are starting perfect.

**Comment by lunny** [comment]
Thanks!

**Pull request merged**
