### PR TITLE
Fix race condition setting connection value

### PR DESCRIPTION
**Pull request by simon3z**
If I am not mistaken if we mark the `WaitGroup` to `Done` before setting the `socket.conn` value, we could hit a race condition in `waitForOpenSocket` (returning `false` for the check `return socket.conn != nil`).

### CODE REVIEW

**Comment by lunny** [comment]
Yes, but I think maybe we could
```Go
func (socket *ftpPassiveSocket) waitForOpenSocket() error {
	socket.wg.Wait()
        if socket.conn != nil {
		return nil
	}
	return socket.err
}
```

**Comment by simon3z** [comment]
> Yes, but I think maybe we could

@lunny you still have a race:

```
thread-2> socket.wg.Wait()
thread-1> socket.wg.Done()
thread-2> if socket.conn != nil  => false
thread-2> return socket.err
thread-1> socket.conn = conn
```

**Comment by phacops** [comment]
How about deferring the `Done` so even in case of an error, the `WaitGroup` knows we're done?

**Comment by simon3z** [comment]
> How about deferring the Done so even in case of an error, the WaitGroup knows we're done?

@phacops yes that's definitely a good idea!

**Comment by lunny** [comment]
closed by #35

**Pull request closed without merging**
